// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIeSev_4ElmLwU0XaJl3LzzUKOVlZTs04',
    appId: '1:1054763309342:android:ef76852dff0639d6f2d10f',
    messagingSenderId: '1054763309342',
    projectId: 'logistix-83bee',
    storageBucket: 'logistix-83bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHizBy3q-yJNFTtMDLUMXF15MSJDuDu0',
    appId: '1:1054763309342:ios:b93128eef9b83388f2d10f',
    messagingSenderId: '1054763309342',
    projectId: 'logistix-83bee',
    storageBucket: 'logistix-83bee.firebasestorage.app',
    iosBundleId: 'com.techsalis.logistix',
  );

}