name: rider
description: Rider module for Logistix
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  adapters:
    git:
      url: https://github.com/Enri-code/flutter-bootstrap-adapters
      ref: v0.5.5

  bootstrap:
    git:
      url: https://github.com/Enri-code/flutter-bootstrap
      ref: v0.5.5

  auth:
    path: ../auth
  logistix_ux:
    path: ../../packages/logistix_ux
  shared:
    path: ../../packages/shared

  flutter_bloc: ^8.1.3
  geolocator: ^14.0.2
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.2
  package_info_plus: ^9.0.0
  freezed_annotation: ^3.1.0

  drift: any
  lucide_icons_flutter: ^3.1.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.7.1
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true